### ISSUE TITLE
Komodo Dragon is now free.

### ISSUE THREAD

**Issue by texium** [lukasmonk/lucaschessR2#125]
On the komodo chess site, they have now made komodo dragon 1 free for anyone, so maybe you could add it.

**Comment by lukasmonk** [comment]
I've asked the chess.com people, I'm waiting for a reply.

**Comment by egBean** [comment]
dragon 1 will be stronger than komodo 14.1?

**Comment by lukasmonk** [comment]
It is an evolution, so it is supposed to be:
http://computerchess.org.uk/ccrl/4040/cgi/compare_engines.cgi?family=Komodo&print=Rating+list&print=Results+table&print=LOS+table&print=Ponder+hit+table&print=Eval+difference+table&print=Comopp+gamenum+table&print=Overlap+table&print=Score+with+common+opponents

**Comment by egBean** [comment]
The advantage is not very obvious

**Comment by lukasmonk** [comment]
The readme states:

Dragon is a huge improvement over all previous Komodo versions, in both standard and MCTS modes, achieved by incorporating the new “NNUE” technology originally developed for the game of shogi. Dragon supports multi-core computers and endgame tablebases. Komodo, the Dragon predecessor, has won many highly respected engine tournaments multiple times, such as TCEC, CCT, the World Computer Chess Championship, the World Blitz and the World Rapid championships. In both standard and MCTS modes, Dragon is about 200 elo stronger than Komodo 14 on one thread and about 170 elo stronger on four threads, based on direct matches at the CCRL blitz time control of 2’ + 1”. Compared to Komodo 14.1 the gains are roughly just ten elo less. We believe that Dragon is the strongest Monte-Carlo engine for most personal computers without high speed GPUs, and is among the top three CPU-based engines. We believe Dragon MCTS can benefit from as many as 64 threads and that it benefits from using many threads as much as standard engines do. While the MCTS version is not yet competitive with normal Dragon in strength, the gap is now only around seventy elo points, and we believe that it is now stronger than the normal version if both are using MultiPV. It defeated Stockfish 12 by more than a hundred game margin in a 3600 game test match when both were set to MultiPV = 4, so we believe that it is the world’s strongest CPU-based engine when analyzing more than three lines at once. Its playing style and move choices are more like Alpha-Zero than like normal engines, meaning that it is generally less materialistic than normal Komodo, in the style of the spectacular World Champion Mikhail Tal. In general, the MCTS moves are more human-like and more tricky for humans to meet than normal Komodo, because Dragon MCTS does not assume that its opponent will always play the move that Komodo would play. Komodo MCTS is the only engine ever to win a public Rapid (not blitz) game giving knight odds to a grandmaster. We now recommend using Komodo or Dragon in MCTS mode for most purposes other than engine vs engine games and perhaps assistance in correspondence games. For game reviews, as a sparring partner, or for preparing openings for over the board play, MCTS is in general the better option, especially when MultiPV is used.

**Comment by lukasmonk** [comment]
I will include it in the next update, chess.com has confirmed that I have permission.
