### ISSUE TITLE
Trying to add a chess engine via command hangs the program indefinitely

### ISSUE THREAD

**Issue by marvk** [lukasmonk/lucaschessR2#45]
Hi,

I have a chess engine running on the JVM, and when I try to add it via command like so
![image](https://user-images.githubusercontent.com/6569856/199804783-a0ca5f57-ed45-412e-9c61-f0afa11be69c.png)

or like so

![image](https://user-images.githubusercontent.com/6569856/199804838-31f7a6aa-b907-49ba-8d5e-fa024277c4d1.png)

Lucas Chess will hang itself indefinitely. 

Trying to start the engine in PowerShell is no problem. It also responds `uciok` to `uci` and `readyok` to `isready`:

![image](https://user-images.githubusercontent.com/6569856/199805389-16e8870a-5455-48cf-a957-ec9f5a5578ef.png)

Not 100% sure this isn't an issue on my end, but maybe someone can help me out here if this is indeed not a bug. I can supply test files if necessary.

**Comment by lukasmonk** [comment]
I have found an error because it tries to write a text file to the Program Files folder and it has no permission
I have fixed it in my development version.
If you want to test, remove Engines.pyc and copy Engines.py in the same folder
Engines.pyc = LucasChessR\bin\Code\Engines\Engines.pyc
Engines.py, unzip: [Engines.zip](https://github.com/lukasmonk/lucaschessR2/files/9932455/Engines.zip)

**Comment by Xyrio** [comment]
i tried it with another java chess engine ( https://github.com/RyanLauQF/BLANK-Chess/releases/tag/v1.3.0 )
and it works if you dont use any quoutes.
the problem is when using single/double quoutes for the 2nd parameter.
