### ISSUE TITLE
Adding external engines doesn't work

### ISSUE THREAD

**Issue by ShabazzKing** [lukasmonk/lucaschessR2#8]
1. In the file selector one can't expand /usr/games/ directory (but for example /usr/bin/ expands well), so I can't choose /usr/games/stockfish file.
2. If I write path to this file manually, Lucas Chess doesn't remember my new engine (in this case Stockfish 12).
3. Lucas Chess then stops launching, unless i remove ~/LucasChessR/UserData/__Config__/ExtEngines.pk file.

**Comment by ShabazzKing** [comment]
Adding external engines doesn't work at all, no matter how you would like to do this, be it by specifying command or by clicking "new" in engines configuration window. Even if i make a symbolic link to an executable, LucasChess doesn't see this symlink. In fact, Lucas Chess doesn't see all executables in /usr/bin/.

**Comment by ShabazzKing** [comment]
Since version 2.02 problem is partially solved. Now I can choose external engine, but the program hangs forever and consumes CPU while showing a message that I should wait for a moment for engine to be added.

**Comment by lukasmonk** [comment]
The problem seems to be that it fails to open the file. Maybe a permissions problem, it's very likely.
I have tried installing an external from the personal folder with no problem.
You can try adding an external engine from the same ones that come with the program, they are in LucasChessR/bin/OS/Engines.
If there is no problem, copy that folder in the same place where there are problems and try it, and if it works, compare permissions.

**Comment by ShabazzKing** [comment]
Maybe the problem is with the size of engine file? I have tried adding stockfish installed from Ubuntu repository, either from /usr/games/ localization or from ~ , and without success. Size of /usr/games/stockfish is 45.1 MiB. I have looked into ~/LucasChessR/bin/OS/linux/Engines/stockfish/ , and engine file here is about 300 KiB.

**Comment by ShabazzKing** [comment]
My version is compatible, by the way it is from official Ubuntu repository.
![Screenshot_20220720_173737](https://user-images.githubusercontent.com/25502034/180024491-323ee144-6279-4876-a3c7-c63e4594308e.png)

**Comment by lukasmonk** [comment]
I can't find a reason, and I'm not able to replicate it.
As a curiosity, version 2.02a of the program includes stockfish version 15.

**Comment by ShabazzKing** [comment]
Did you try to make virtual machine with Ubuntu Jammy Jellyfish, then to install stockfish via package manager (apt install stockfish), then to add this engine (/usr/games/stockfish) to Lucas Chess installed in this VM?

I'm sure you would replicate this bug, if you follow my steps.

**Comment by ShabazzKing** [comment]
That's what I had in the terminal after launching LucasChess from terminal and trying to add stockfish:

./stockfish: /home/panlukasz/LucasChessR/bin/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./stockfish)

I think the version of libstdc++ included in LucasChess is too outdated for stockfish compiled by Ubuntu. The modification date of ~/LucasChessR/bin/libstdc++.so.6 is 17 october 2020. The modification date of /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30 in my system is 19 march 2022, so it is way more recent than version included in LucasChess. And I think that the LucasChess's version is used to load /usr/games/stockfish, which causes incompatibilities.

**Comment by ShabazzKing** [comment]
The conclusion:
You should track changes in libraries included in LucasChess and update them if the new upstream version is available.

**Comment by lukasmonk** [comment]
LucasChess is built with an old version of glibc with the intention of being compatible with most distributions, compatible with versions that use very few resources.
I have a VM Ubuntu 20.04 distribution, I downloaded the official stockfish version and it doesn't work, because of the glibc, then I downloaded the sources and compiled them, generating the 47Mb file. Then I launched LucasChess and added it without problems as external engine. That is to say it works with the versions compiled with gclib 2.26, and the ones of the system itself.
So it's not a size problem.
Nor is it a problem of the gclib, as long as it is smaller or equal to the system's own gclib.
I don't know what the problem is with version 14 generated on your system.

**Comment by lukasmonk** [comment]
I need help to create a distribution that can solve all of these fastidiosos problemas, no necesito teoria sino alguien que se ponga el buzo de trabajo y establezca una linea de compilacion que resuelva todo sestos problemas específicos de Linux.
